name: Build FTP_Deploy_Client

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:

    runs-on: windows-latest

    env:
      PROJECT_PATH: FTP_Deploy_Client.csproj
      OUTPUT_DIR: publish
      CONFIGURATION: Release
      RUNTIME: win-x64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 9.0 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore $env:PROJECT_PATH

    - name: Build and publish (single file, self-contained)
      run: >
        dotnet publish $env:PROJECT_PATH
        -c $env:CONFIGURATION
        -r $env:RUNTIME
        --self-contained true
        /p:PublishSingleFile=true
        /p:IncludeNativeLibrariesForSelfExtract=true
        /p:DebugType=None
        /p:DebugSymbols=false
        -o $env:OUTPUT_DIR

    - name: Archive build output
      uses: actions/upload-artifact@v4
      with:
        name: FTP_Deploy_Client_${{ env.RUNTIME }}
        path: ${{ env.OUTPUT_DIR }}
